apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: target-wp
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io