apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: reader
        image: abhishekkamat27/grpc_reader:ip5
        command: ["/bin/sh", "-c"]
        args: [ "./client && tail -f /dev/null" ]
        env:
          - name: GRPC_SERVER_ADDR
            value: "10.15.170.49:50051"
        securityContext:
          privileged: true
        volumeDevices:
        - name: diskreader-pvc
          devicePath: /dev/xvda
      volumes:
      - name: diskreader-pvc
        persistentVolumeClaim:
          claimName: diskreader-pvc
      imagePullSecrets:
      - name: my-registry-secret
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diskreader-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName:  default-storageclass
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: source-sql
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: source-sql
  namespace: default
spec:
  volumeSnapshotClassName: default-snapshotclass
  source:
    persistentVolumeClaimName:  wp-pv-claim
